FROM ubuntu:bionic
LABEL maintainer="sig-platform@spinnaker.io"
COPY igor-web/build/install/igor /opt/igor
RUN apt-get update && apt-get -y install openjdk-11-jre-headless wget
RUN adduser --system --uid 10111 --group spinnaker
RUN mkdir -p /opt/igor/plugins && chown -R spinnaker:nogroup /opt/igor/plugins
USER spinnaker
CMD ["/opt/igor/bin/igor"]
