FROM alpine:3.11
LABEL maintainer="sig-platform@spinnaker.io"
COPY igor-web/build/install/igor /opt/igor
RUN apk --no-cache add --update bash openjdk11-jre
RUN addgroup -S -g 10111 spinnaker
RUN adduser -S -G spinnaker -u 10111 spinnaker
RUN mkdir -p /opt/igor/plugins && chown -R spinnaker:nogroup /opt/igor/plugins
USER spinnaker
CMD ["/opt/igor/bin/igor"]
